#!/bin/bash

# regenerate-bootstrap-token runs kubeadm create token and put it into
# etcd on the master nodes and registers the PKI into ETCD. Tokens are
# valid 24h. if scaling worker nodes after this delay dont forget to
# regenerate a valid token before

set -eo pipefail

if [ "$MASTER_MODE" != "1" ]; then
    echo "not a master. should not be called" >&2
    exit 1
fi

echo "Create new bootstrap token & putting it into etcd." >&2
export ETCDCTL_API=3
/opt/k8s/bin/etcdctl --cacert "$ETCD_CA_FILE" \
                     --cert "$ETCD_CERT_FILE" \
                     --key "$ETCD_KEY_FILE" \
                     --endpoints "$ETCD_ENDPOINTS" \
                     put "$BOOTSTRAP_TOKEN_ETCD_KEY" "$(/opt/k8s/bin/kubeadm token create)"
