all: coreos centos7 ubuntu1604 ubuntu1804

coreos:
	@./build.sh coreos

centos7:
	@./build.sh centos7

ubuntu1804:
	@./build.sh ubuntu1804

ubuntu1604:
	@./build.sh ubuntu1604

publish-coreos:
	@./publish.sh coreos

publish-centos7:
	@./publish.sh centos7

publish-ubuntu1604:
	@./publish.sh ubuntu1604

publish-ubuntu1804:
	@./publish.sh ubuntu1804
